[window]
padding = { x = 12, y = 10 }
opacity = 0.88
dynamic_padding = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Rose Pine dark
[colors.primary]
background = "#191724"
foreground = "#e0def4"

[colors.cursor]
text = "#191724"
cursor = "#e0def4"

[colors.vi_mode_cursor]
text = "#191724"
cursor = "#ebbcba"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black   = "#26233a"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.bright]
black   = "#6e6a86"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"
